### PR TITLE
Some follow-me fixes

### LINKED ISSUE #408: Follow Me example behaviour has changed in latest firmware
Previously flew spirals as shown here: https://sdk.dronecode.org/en/examples/follow_me.html

Now it flies a straight line somewhat south, while spinning a bit: 
image

I tried this for gazebo and jmavsim using current firmware and DroneCore, on a real machine and in VM.

### PR DESCRIPTION
**Pull request by julianoes**
This fixes #408 and makes the example a bit easier to understand. The path is changed from a semi-circular path (which I had broken in the meantime) to just a square. Also, we're now following from behind which is most intuitive to start with.

### CODE REVIEW

File: example/follow_me/fake_location_provider.cpp [hunk 1]
```diff
@@ -37,39 +37,30 @@ void FakeLocationProvider::stop()
...
-        }
-        if (count_++ < MAX_LOCATIONS) {
-            location_callback_(latitude_deg_, longitude_deg_);
-            longitude_deg_ += LONGITUDE_DEG_PER_METER * 3;
+        } else {
+            // We're done.
+            should_exit_ = true;
         }
         sleep_for(seconds(1));
+        ++count_;
```
Comment (JonasVautherin) [inline example/follow_me/fake_location_provider.cpp]: Yep!
